#!/usr/bin/env python3
"""FieldLab's Mac half: receive the phone's always-on stream, keep it, and show it.

    python3 serve.py            # http://127.0.0.1:8212/
    python3 serve.py 8300       # any port

The phone posts to `<server URL>/api/stream/chunk`; set the server URL in the app's Stream settings.
Behind a reverse proxy that mounts it under a path prefix (GATEWAY_PREFIXES), every route here is
still rooted at `/`, and the web page fetches by RELATIVE path so it works both ways.

What it owns
------------
* `POST /api/stream/chunk`  — one spool file from the phone: a raw-DEFLATE body whose first line
  is a JSON header and the rest is `raw.csv` (same columns as an export). Stored DECOMPRESSED
  under `streams/<device>/<stream>/chunks/<seq>.csv`, one manifest line appended per chunk, and
  acknowledged with the sequence numbers this server has NOT seen — so a gap is reported the
  moment it exists. Idempotent: a retried upload of the same bytes is a `duplicate`, not a second
  chunk. The gateway may retry a POST once, so that is load-bearing.
* `POST /api/stream/hello`  — the phone's settings and identity at Start. Optional; a chunk
  header carries enough to reconstruct a stream without it.
* Each chunk header may carry an `aux` block (battery, thermal state, barometric pressure, free
  disk) and a structured `emitter` stamp (carrier, code, chip) when the phone was running its own
  positive control. Both are optional — an older chunk without them is not an error.
* `GET  /api/events`        — SSE: a `chunk` event per arrival plus a heartbeat, so the page can
  redraw when something lands rather than polling.
* `GET  /api/samples`       — a time window of samples for one device, optionally bin-averaged,
  with the dropped-sample gaps the window contains. Served from disk, never from a second copy.
* `GET  /api/findings`      — the consuming analysis's summary, generated by its `run.py summary`
  and served as a static file. **It reads cached artefacts and never fetches.**
* `GET  /api/station`       — the latest reference-station profile, cached from the last `station`
  job of the consuming analysis.
* `GET  /api/register`      — the signal register: every signal ever logged for a device, with its
  fingerprint, its automatic test results, and which manual tests are still outstanding.
* `POST /api/register/confirm` — record that a person actually ran a manual test, and what happened.
* `GET  /api/watch`        — the consuming analysis's live reading of the line it is watching (its
  `run.py watch`), shelled out to that analysis's venv and briefly cached, because the page polls it.
* `GET  /api/runbook`      — the manual tests as coached steps, what has been ticked, and what is
  safe to do right now given `/api/watch`. Imported directly: `runbook.py` is stdlib on purpose.
* `POST /api/runbook/step` — tick or untick one step, recording the GATE STATE at that moment.
* `POST /api/runbook/reset`— archive an attempt and start that test again. Appends, never deletes.
* `GET  /watch`            — the consuming analysis's own page, if it ships one (`CLAIM_WEB`).
* `GET  /api/alerts`        — the most recent "what in this record is not noise" scan for a device,
  cached from the last `alerts` job. Carries the window it was computed over and when.
* `GET  /api/bands`         — the band registry, PARSED OUT OF `BandRegistry.swift` at request
  time. One source of truth for "what is a known band"; the web page reads this, not a copy.
* `POST /api/analyze`       — run `analysis/run.py <command>` over a window of stream, in the
  sidecar's own venv, as a job. The server itself is stdlib-only; numpy lives in `analysis/`.

What it refuses
---------------
* any URL segment named `research`, `subjects` or `recordings` (proxies that guard private data
  often refuse those names, and a route that works only on localhost is a trap);
* static reads under `streams/` (the data folder is not on the URL surface) and any `.py`;
* a chunk whose SHA-256 does not match its header, whose header says a different format, or
  whose decompressed size exceeds `MAX_CHUNK_BYTES`;
* a `device` or `stream` id containing anything but `[A-Za-z0-9_-]`.

There is no authentication. Run it on a private network (a tailnet, a LAN) and never expose it to
the internet: anyone who can reach it can read the stream and add to it.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import queue
import re
import subprocess
import sys
import threading
import time
import zlib
from datetime import datetime, timezone
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlsplit

HERE = Path(__file__).resolve().parent


def _load_local_env(path: Path) -> None:
    """KEY=VALUE lines from `fieldlab.env` (git-ignored) beside this file, for settings a launcher cannot
    pass as environment variables. The real environment wins; relative paths are resolved from here."""
    if not path.is_file():
        return
    for line in path.read_text().splitlines():
        key, sep, value = line.strip().partition("=")
        if not sep or key.startswith("#") or not key.startswith("FIELDLAB_") or key in os.environ:
            continue
        value = value.strip().strip('"')
        if key in ("FIELDLAB_ANALYSIS", "FIELDLAB_STREAMS", "FIELDLAB_DESIGN") and value:
            value = str((path.parent / value).resolve())
        os.environ[key] = value


_load_local_env(HERE / "fieldlab.env")


#: URL prefixes a reverse proxy may mount this app under, stripped so every route works both direct and
#: proxied: the folder name, the app's default path (`/biomimetic-radar`), and any listed in
#: FIELDLAB_PREFIXES (comma-separated) for a deployment that serves it under other names.
GATEWAY_PREFIXES = (f"/{HERE.name}", "/biomimetic-radar", *(
    "/" + p.strip("/ ") for p in os.environ.get("FIELDLAB_PREFIXES", "").split(",") if p.strip("/ ")))

sys.path.insert(0, str(HERE))
import tools_path  # noqa: E402

DEFAULT_PORT = 8212
WEB = HERE / "web"
# Overridable so the self-tests can run against a scratch store without touching real data.
STREAMS = Path(os.environ.get("FIELDLAB_STREAMS", HERE / "streams"))
def _analysis_dir() -> Path:
    """Where the numpy-side analysis lives: with the research that interprets a recording, not here.

    This tool owns the phone, the wire format, the stream store and the dashboard. What a recording
    means belongs to whichever study is using it, which brings its own analysis:

      1. $FIELDLAB_ANALYSIS, if set: the study's analysis directory (its `run.py`, its `.venv`, and
         optionally a `../watch/` page);
      2. otherwise the local analysis/ directory, which only holds the chunk-format fixtures.

    Nothing here IMPORTS the analysis — `/api/analyze` shells out to its run.py in its own venv, so
    this server stays stdlib and a missing analysis degrades to a disabled button rather than an
    import error.
    """
    env = os.environ.get("FIELDLAB_ANALYSIS")
    return Path(env) if env else HERE / "analysis"


ANALYSIS = _analysis_dir()
ANALYSIS_PY = ANALYSIS / ".venv" / "bin" / "python"
#: A consuming entry may ship its OWN focused page -- one claim, one line, the tests that settle it
#: -- and this server mounts it at /watch without knowing anything about it. The dashboard here is
#: generic (what came in); a claim page is not, and belongs with the claim. A second consumer (a
#: coil) brings its own `watch/` and gets the same mount for free.
CLAIM_WEB = ANALYSIS.parent / "watch"
BAND_REGISTRY_SWIFT = HERE / "BiomimeticRadar" / "Processing" / "BandRegistry.swift"
INTERFERENCE_SWIFT = HERE / "BiomimeticRadar" / "Processing" / "InterferenceRegistry.swift"
FORMAT = "fieldlab-stream/1"
CHUNK_CONTENT_TYPE = "application/x-fieldlab-chunk"
# POSTs must carry one of these. A browser can send text/plain, a form, or no type across origins
# without asking first; anything else needs a preflight, which this server never grants.
POST_CONTENT_TYPES = ("application/json", CHUNK_CONTENT_TYPE)


class ChunkConflict(ValueError):
    """A different chunk already holds this seq. The stored one is the only copy, so it is kept."""
MAX_CHUNK_BYTES = 64 * 1024 * 1024
MAX_JSON_BYTES = 256 * 1024          # hello, analyze, runbook and register bodies are small JSON
MAX_RUNNING_JOBS = 2                 # each analysis job may run for up to 30 minutes
ID_RE = re.compile(r"^[A-Za-z0-9_-]{1,64}$")
# The stream CSV's columns, by name. `analysis/fieldlab/session.py` reads these same names.
CSV_HEADER = ("monotonic_s,wall_clock,mx_uT,my_uT,mz_uT,magnitude_uT,ax_g,ay_g,az_g,"
              "gx_rads,gy_rads,gz_rads,qx,qy,qz,qw,orientation,latitude,longitude")
ANALYZE_COMMANDS = ("structure", "context", "channel", "jitter", "baseline", "census",
                    "coupling", "alerts", "identify", "station")

DESIGN = tools_path.DESIGN
DESIGN_PUBLIC = {
    "/design/design.css": DESIGN / "design.css",
    "/design/design.js": DESIGN / "design.js",
    "/design/tokens.json": DESIGN / "tokens.json",
    "/design/icons/polarize-icons.svg": DESIGN / "icons" / "polarize-icons.svg",
}


# ----------------------------------------------------------------------------- helpers

def _iso_to_epoch(text: str) -> float:
    text = text.strip().replace("Z", "+00:00")
    value = datetime.fromisoformat(text)
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.timestamp()


def _epoch_to_iso(value: float) -> str:
    return datetime.fromtimestamp(value, tz=timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(path.name + ".partial")
    with open(temp, "wb") as handle:
        handle.write(data)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temp, path)


def _valid_id(value) -> bool:
    return isinstance(value, str) and bool(ID_RE.match(value))


# ----------------------------------------------------------------------------- the store

class Store:
    """Everything under `streams/`. One lock; disk is the truth, memory is an index of it."""

    def __init__(self, root: Path):
        self.root = root
        self.lock = threading.RLock()
        self.listeners: list[queue.Queue] = []
        root.mkdir(parents=True, exist_ok=True)

    # -- paths
    def stream_dir(self, device: str, stream: str) -> Path:
        return self.root / device / stream

    def manifest_path(self, device: str, stream: str) -> Path:
        return self.stream_dir(device, stream) / "manifest.jsonl"

    # -- reading
    def manifest(self, device: str, stream: str) -> list[dict]:
        path = self.manifest_path(device, stream)
        if not path.exists():
            return []
        rows = []
        for line in path.read_text().splitlines():
            line = line.strip()
            if line:
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError:
                    continue  # a torn last line from a crash mid-append; the chunk file is still there
        # One row per seq; a retry after a lost row can log it again (ingest), so keep the last.
        by_seq: dict[int, dict] = {}
        for row in rows:
            by_seq[row["seq"]] = row
        return [by_seq[k] for k in sorted(by_seq)]

    @staticmethod
    def missing(rows: list[dict]) -> list[int]:
        if not rows:
            return []
        have = {r["seq"] for r in rows}
        top = max(have)
        return [s for s in range(top + 1) if s not in have]

    def devices(self) -> list[str]:
        return sorted(p.name for p in self.root.iterdir() if p.is_dir() and _valid_id(p.name))

    def streams(self, device: str) -> list[str]:
        d = self.root / device
        if not d.is_dir():
            return []
        return sorted(p.name for p in d.iterdir() if p.is_dir() and _valid_id(p.name))

    def stream_summary(self, device: str, stream: str) -> dict:
        rows = self.manifest(device, stream)
        info = {}
        meta = self.stream_dir(device, stream) / "stream.json"
        if meta.exists():
            try:
                info = json.loads(meta.read_text())
            except json.JSONDecodeError:
                info = {}
        if rows:
            first, last = rows[0], rows[-1]
            summary = {
                "device": device, "stream": stream,
                "chunks": len(rows), "missing": self.missing(rows),
                "samples": sum(r.get("sampleCount", 0) for r in rows),
                "from": first["startedAt"], "to": last["endedAt"],
                "fromEpoch": _iso_to_epoch(first["startedAt"]), "toEpoch": _iso_to_epoch(last["endedAt"]),
                "rateHz": last.get("achievedRateHz"),
                "emitter": any(r.get("emitter") for r in rows),
                # The phone's covariates from the most recent chunk: battery, thermal, barometric
                # pressure, free disk. Absent from older chunks, which is not an error.
                "aux": last.get("aux"),
                "lastReceivedAt": last.get("receivedAt"),
            }
        else:
            summary = {"device": device, "stream": stream, "chunks": 0, "missing": [], "samples": 0}
        summary["info"] = info
        return summary

    def status(self) -> dict:
        out = []
        for device in self.devices():
            streams = [self.stream_summary(device, s) for s in self.streams(device)]
            streams.sort(key=lambda s: s.get("fromEpoch", 0))
            latest = streams[-1] if streams else None
            out.append({
                "device": device,
                "name": (latest or {}).get("info", {}).get("deviceName") if latest else None,
                "streams": streams,
                "latest": latest,
            })
        return {"devices": out, "now": time.time(), "analysisVenv": ANALYSIS_PY.exists()}

    # -- writing
    def ingest(self, body: bytes, compression: str) -> dict:
        if compression in ("deflate-raw", "deflate"):
            decomp = zlib.decompressobj(-15)
            try:
                file = decomp.decompress(body, MAX_CHUNK_BYTES + 1)
            except zlib.error as exc:
                raise ValueError(f"deflate: {exc}") from exc
            if len(file) > MAX_CHUNK_BYTES or decomp.unconsumed_tail:
                raise ValueError("chunk too large")
        elif compression in ("none", "identity", ""):
            file = body
        else:
            raise ValueError(f"unknown compression {compression!r}")
        newline = file.find(b"\n")
        if newline < 0:
            raise ValueError("no header line")
        try:
            header = json.loads(file[:newline])
        except json.JSONDecodeError as exc:
            raise ValueError(f"header is not JSON: {exc}") from exc
        if header.get("format") != FORMAT:
            raise ValueError(f"format {header.get('format')!r} is not {FORMAT}")
        device, stream, seq = header.get("deviceID"), header.get("streamID"), header.get("seq")
        if not (_valid_id(device) and _valid_id(stream) and isinstance(seq, int) and seq >= 0):
            raise ValueError("bad deviceID / streamID / seq")
        # Every reader of the manifest does arithmetic on these; one bad row used to break /api/status.
        if not (isinstance(header.get("sampleCount"), int) and header["sampleCount"] >= 0):
            raise ValueError("sampleCount must be a non-negative integer")
        for key in ("startedAt", "endedAt"):
            try:
                _iso_to_epoch(header[key])
            except (KeyError, AttributeError, TypeError, ValueError):
                raise ValueError(f"{key} must be an ISO-8601 time") from None
        csv_bytes = file[newline + 1:]
        digest = hashlib.sha256(csv_bytes).hexdigest()
        if header.get("sha256") != digest:
            raise ValueError("sha256 mismatch: the bytes received are not the bytes the phone described")
        first_line = csv_bytes.split(b"\n", 1)[0].decode("utf-8", "replace")
        if first_line.strip() != CSV_HEADER:
            raise ValueError("CSV header is not the raw.csv column set")

        with self.lock:
            chunk_path = self.stream_dir(device, stream) / "chunks" / f"{seq:06d}.csv"
            duplicate = False
            if chunk_path.exists():
                existing = hashlib.sha256(chunk_path.read_bytes()).hexdigest()
                if existing != digest:
                    raise ChunkConflict(f"seq {seq} is already stored with different bytes; the stored chunk is kept")
                duplicate = True
            # A crash between writing the file and appending its row left the chunk on disk but out of
            # the manifest, and the phone's retry then read as a duplicate. The retry writes the row.
            logged = duplicate and any(r.get("seq") == seq for r in self.manifest(device, stream))
            if not duplicate:
                _atomic_write(chunk_path, csv_bytes)
            if not logged:
                row = {k: header.get(k) for k in ("seq", "startedAt", "endedAt", "firstMonotonic", "lastMonotonic",
                                                  "sampleCount", "requestedRateHz", "achievedRateHz", "emitter",
                                                  "aux", "sha256", "deviceName", "deviceModel", "systemVersion",
                                                  "appVersion")}
                row["receivedAt"] = _epoch_to_iso(time.time())
                row["bytes"] = len(csv_bytes)
                with open(self.manifest_path(device, stream), "a") as handle:
                    handle.write(json.dumps(row, separators=(",", ":")) + "\n")
                    handle.flush()
                    os.fsync(handle.fileno())
                self._touch_stream_json(device, stream, header)
            rows = self.manifest(device, stream)
            missing = self.missing(rows)

        event = {
            "device": device, "stream": stream, "seq": seq, "duplicate": duplicate,
            "startedAt": header.get("startedAt"), "endedAt": header.get("endedAt"),
            "sampleCount": header.get("sampleCount"), "achievedRateHz": header.get("achievedRateHz"),
            "emitter": header.get("emitter"), "missing": missing[-50:], "chunks": len(rows),
        }
        if not duplicate:
            self.publish("chunk", event)
        return {"ok": True, "seq": seq, "duplicate": duplicate, "stored": str(chunk_path.relative_to(self.root)),
                "missing": missing[-50:], "message": f"chunk {seq} {'already held' if duplicate else 'stored'}; "
                f"{len(rows)} in stream, {len(missing)} missing"}

    def _touch_stream_json(self, device: str, stream: str, header: dict) -> None:
        path = self.stream_dir(device, stream) / "stream.json"
        info = {}
        if path.exists():
            try:
                info = json.loads(path.read_text())
            except json.JSONDecodeError:
                info = {}
        for key in ("deviceName", "deviceModel", "systemVersion", "appVersion", "requestedRateHz"):
            if header.get(key) is not None:
                info[key] = header[key]
        info.setdefault("firstSeenAt", _epoch_to_iso(time.time()))
        info["lastChunkAt"] = _epoch_to_iso(time.time())
        info["deviceID"], info["streamID"] = device, stream
        _atomic_write(path, json.dumps(info, indent=2, sort_keys=True).encode())

    def hello(self, payload: dict) -> dict:
        device, stream = payload.get("deviceID"), payload.get("streamID")
        if not (_valid_id(device) and _valid_id(stream)):
            raise ValueError("bad deviceID / streamID")
        with self.lock:
            path = self.stream_dir(device, stream) / "stream.json"
            info = {}
            if path.exists():
                try:
                    info = json.loads(path.read_text())
                except json.JSONDecodeError:
                    info = {}
            info.update({k: v for k, v in payload.items() if k not in ("deviceID", "streamID")})
            info["deviceID"], info["streamID"] = device, stream
            info.setdefault("firstSeenAt", _epoch_to_iso(time.time()))
            info["helloAt"] = _epoch_to_iso(time.time())
            _atomic_write(path, json.dumps(info, indent=2, sort_keys=True).encode())
        self.publish("hello", {"device": device, "stream": stream, "deviceName": payload.get("deviceName")})
        return {"ok": True, "message": f"hello {device}/{stream}"}

    # -- samples
    def samples(self, device: str, t0: float, t1: float, step: int = 1, stream: str | None = None) -> dict:
        """Rows whose wall time falls in [t0, t1], as columns. `step > 1` bin-averages."""
        cols = {"t": [], "mx": [], "my": [], "mz": [], "mag": []}
        chunks_used = 0
        emitter = False
        streams = [stream] if stream else self.streams(device)
        for s in streams:
            for row in self.manifest(device, s):
                a, b = _iso_to_epoch(row["startedAt"]), _iso_to_epoch(row["endedAt"])
                if b < t0 or a > t1:
                    continue
                path = self.stream_dir(device, s) / "chunks" / f"{row['seq']:06d}.csv"
                if not path.exists():
                    continue
                chunks_used += 1
                emitter = emitter or bool(row.get("emitter"))
                anchor = a - float(row.get("firstMonotonic") or 0.0)
                with open(path) as handle:
                    next(handle, None)
                    for line in handle:
                        parts = line.split(",", 6)
                        if len(parts) < 6:
                            continue
                        try:
                            t = anchor + float(parts[0])
                            mx, my, mz, mag = (float(v) for v in parts[2:6])
                        except ValueError:          # an empty or garbled field drops the row
                            continue
                        if t < t0 or t > t1:
                            continue
                        cols["t"].append(t)
                        cols["mx"].append(mx)
                        cols["my"].append(my)
                        cols["mz"].append(mz)
                        cols["mag"].append(mag)
        # sort by time across streams (streams do not overlap, but be safe)
        if cols["t"] and any(cols["t"][i] > cols["t"][i + 1] for i in range(len(cols["t"]) - 1)):
            order = sorted(range(len(cols["t"])), key=cols["t"].__getitem__)
            for k in cols:
                cols[k] = [cols[k][i] for i in order]
        gaps = []
        rate = None
        t = cols["t"]
        if len(t) > 2:
            dts = sorted(t[i + 1] - t[i] for i in range(len(t) - 1) if t[i + 1] > t[i])
            if dts:
                median = dts[len(dts) // 2]
                rate = 1 / median if median > 0 else None
                for i in range(len(t) - 1):
                    if t[i + 1] - t[i] > 3 * median:
                        gaps.append([t[i], t[i + 1]])
        if step > 1 and t:
            binned = {k: [] for k in cols}
            for i in range(0, len(t), step):
                j = min(i + step, len(t))
                n = j - i
                for k in cols:
                    binned[k].append(sum(cols[k][i:j]) / n)
            cols = binned
        return {"device": device, "from": t0, "to": t1, "n": len(cols["t"]), "step": step, "rateHz": rate,
                "gaps": gaps, "chunks": chunks_used, "emitter": emitter, **cols}

    # -- events
    def subscribe(self) -> queue.Queue:
        q: queue.Queue = queue.Queue(maxsize=256)
        with self.lock:
            self.listeners.append(q)
        return q

    def unsubscribe(self, q: queue.Queue) -> None:
        with self.lock:
            if q in self.listeners:
                self.listeners.remove(q)

    def publish(self, event: str, data: dict) -> None:
        with self.lock:
            listeners = list(self.listeners)
        for q in listeners:
            try:
                q.put_nowait((event, data))
            except queue.Full:
                pass


# ----------------------------------------------------------------------------- bands from Swift

# The band catalogue is parsed by `analysis/fieldlab/bands.py` — one parser, imported here rather
# than a second regex that could drift from it. That module is stdlib-only for exactly this reason.
try:
    import bands as _band_module          # this repo owns the catalogue and its reader
except Exception:  # noqa: BLE001 — a failed import empties /api/bands rather than stopping the server
    _band_module = None


_SRC_RE = re.compile(
    r'Source\(id:\s*"(?P<id>[^"]+)",\s*name:\s*"(?P<name>[^"]+)",\s*origin:\s*\.(?P<origin>\w+),\s*character:\s*\.(?P<character>\w+),.*?location:\s*"(?P<location>[^"]*)",\s*effect:\s*"(?P<effect>(?:[^"\\]|\\.)*)",\s*tell:\s*"(?P<tell>(?:[^"\\]|\\.)*)",\s*mitigation:\s*"(?P<mitigation>(?:[^"\\]|\\.)*)",\s*suggestedFilter:\s*(?P<filter>SuggestedFilter\([^)]*\)|nil),\s*orderOfMagnitude:\s*"(?P<order>[^"]*)"',
    re.S)
_FILTER_RE = re.compile(r'kind:\s*\.(?P<kind>\w+),\s*hz:\s*(?P<hz>[0-9.eE+-]+|nil),\s*harmonics:\s*(?P<harm>\[[^\]]*\]|nil)')


def interference_from_swift(path: Path = INTERFERENCE_SWIFT) -> list[dict]:
    """The phone-interference catalogue IS the Swift file — no second copy to drift."""
    if not path.exists():
        return []
    text = path.read_text()
    out = []
    for m in _SRC_RE.finditer(text):
        keys = ("id", "name", "origin", "character", "location", "effect", "tell", "mitigation", "order")
        entry = {k: m.group(k) for k in keys}
        entry["orderOfMagnitude"] = entry.pop("order")
        for k in ("effect", "tell", "mitigation"):
            entry[k] = entry[k].replace('\\"', '"')
        fm = m.group("filter")
        if fm == "nil":
            entry["suggestedFilter"] = None
        else:
            f = _FILTER_RE.search(fm)
            if f:
                hz = None if f.group("hz") == "nil" else float(f.group("hz"))
                harm = None
                if f.group("harm") != "nil":
                    harm = [float(x) for x in re.findall(r'[0-9.eE+-]+', f.group("harm"))]
                entry["suggestedFilter"] = {"kind": f.group("kind"), "hz": hz, "harmonics": harm}
            else:
                entry["suggestedFilter"] = None
        out.append(entry)
    return out


def bands_from_swift(path: Path = BAND_REGISTRY_SWIFT) -> list[dict]:
    """The band registry IS the Swift file, read by `fieldlab.bands`. No second copy to drift."""
    if _band_module is None or not path.exists():
        return []
    return [{"id": b.id, "label": b.label, "lowHz": b.low_hz, "highHz": b.high_hz,
             "family": b.family, "defaultPolicy": b.default_policy, "rank": b.rank}
            for b in _band_module.BANDS]


# ----------------------------------------------------------------------------- analysis jobs

#: The most recent `alerts` result per device, so the page can show a banner without re-running a
#: two-minute job on every load. It carries the window it was computed over and when — an alert
#: with no window is a claim about nothing in particular.
LATEST_ALERTS: dict[str, dict] = {}

#: The most recent professional-station reference profile, keyed by device. Cached the same way as
#: the alerts, and carrying its source so the page can say where a number came from.
LATEST_STATION: dict[str, dict] = {}


class Jobs:
    """`analysis/run.py` as subprocesses. The server stays stdlib; numpy lives in the venv."""

    def __init__(self):
        self.lock = threading.Lock()
        self.jobs: dict[str, dict] = {}
        self.counter = 0

    def start(self, command: str, device: str, t0: float, t1: float, extra: list[str]) -> dict:
        if command not in ANALYZE_COMMANDS:
            raise ValueError(f"command must be one of {ANALYZE_COMMANDS}")
        if not _valid_id(device):
            raise ValueError("bad device")
        if not ANALYSIS_PY.exists():
            raise ValueError("analysis venv missing — see analysis/README.md")
        if not all(math.isfinite(t) and 0 <= t < 4e9 for t in (t0, t1)) or t0 > t1:
            raise ValueError("from/to must be epoch seconds, with from <= to")
        # Every value is a flag's argument: nothing may reach run.py as a positional of its own.
        for i, x in enumerate(extra):
            if not x.startswith("-") and (i == 0 or not extra[i - 1].startswith("-")):
                raise ValueError(f"{x!r} is not the value of a flag")
        if command == "station":
            # A station profile is not a window of THIS device's stream — it reads a remote archive.
            argv = [str(ANALYSIS_PY), str(ANALYSIS / "run.py"), "station", *extra]
        else:
            argv = [str(ANALYSIS_PY), str(ANALYSIS / "run.py"), command, "--stream", str(STREAMS / device),
                    "--from", _epoch_to_iso(t0), "--to", _epoch_to_iso(t1), *extra]
        with self.lock:
            if sum(j["state"] == "running" for j in self.jobs.values()) >= MAX_RUNNING_JOBS:
                raise ValueError(f"{MAX_RUNNING_JOBS} jobs are already running; wait for one to finish")
            self.counter += 1
            job_id = f"job-{self.counter:04d}"
            job = {"id": job_id, "command": command, "device": device, "from": t0, "to": t1,
                   "state": "running", "startedAt": time.time(), "output": "", "returncode": None}
            self.jobs[job_id] = job
        threading.Thread(target=self._run, args=(job_id, argv), daemon=True).start()
        # What ran, without this machine's paths.
        shown = ["run.py", *(f"streams/{device}" if a == str(STREAMS / device) else a for a in argv[2:])]
        return {"ok": True, "job": job_id, "argv": shown}

    def _run(self, job_id: str, argv: list[str]) -> None:
        try:
            proc = subprocess.run(argv, capture_output=True, text=True, timeout=1800, cwd=str(HERE))
            output, code = (proc.stdout or "") + (("\n[stderr]\n" + proc.stderr) if proc.stderr else ""), proc.returncode
        except subprocess.TimeoutExpired:
            output, code = "timed out after 1800 s", -1
        except Exception as exc:  # noqa: BLE001
            output, code = f"failed to start: {exc}", -1
        with self.lock:
            job = self.jobs[job_id]
            job.update(state="done" if code == 0 else "failed", output=output[-200_000:], returncode=code,
                       endedAt=time.time())
            command, device = job["command"], job["device"]
            window = (job["from"], job["to"])
        if code == 0 and command == "station":
            try:
                LATEST_STATION[device] = dict(json.loads(output), computedAt=time.time(), job=job_id)
                STORE.publish("station", {"device": device})
            except (json.JSONDecodeError, TypeError, ValueError):
                pass
        if code == 0 and command == "alerts":
            # Cache the parsed banner payload. A parse failure is not fatal — the job's raw output is
            # still there to read, and a banner that cannot be built is simply not shown.
            try:
                parsed = json.loads(output)
                LATEST_ALERTS[device] = {
                    "device": device, "from": window[0], "to": window[1],
                    "computedAt": time.time(), "job": job_id,
                    "alerts": parsed.get("alerts", {}),
                    "minimumDetectableNt": parsed.get("minimum_detectable_nt"),
                }
                STORE.publish("alerts", {"device": device,
                                         "count": parsed.get("alerts", {}).get("count", 0)})
            except (json.JSONDecodeError, AttributeError):
                pass
        STORE.publish("job", {"id": job_id, "state": self.jobs[job_id]["state"]})

    def list(self) -> list[dict]:
        with self.lock:
            return [dict(j, output=(j["output"][-4000:] if j["state"] == "running" else j["output"]))
                    for j in sorted(self.jobs.values(), key=lambda j: j["startedAt"], reverse=True)]


STORE = Store(STREAMS)
JOBS = Jobs()


# ----------------------------------------------------------------------------- HTTP

class WatchCache:
    """`run.py watch` behind a short TTL.

    The claim page polls this, and a subprocess per poll per open tab is a lot of interpreter
    starts for a number that only changes when a chunk lands. The TTL is deliberately shorter than
    the shortest chunk setting (5 s), so a fresh chunk is never hidden behind a stale reading.

    Every entry carries the age of the window it describes. **A scan describes a window, never
    "now"** -- the same rule `/api/alerts` follows, and the single most misreadable thing on a page
    that updates itself.
    """

    TTL_S = 4.0

    def __init__(self):
        self._lock = threading.Lock()
        self._hot: dict[tuple[str, int], tuple[float, dict]] = {}

    def get(self, device: str, seconds: int) -> dict:
        key = (device, seconds)
        now = time.time()
        with self._lock:
            hit = self._hot.get(key)
            if hit and now - hit[0] < self.TTL_S:
                return dict(hit[1], cached=True)
        payload = self._run(device, seconds)
        with self._lock:
            self._hot[key] = (now, payload)
        return dict(payload, cached=False)

    def _run(self, device: str, seconds: int) -> dict:
        if not ANALYSIS_PY.exists():
            return {"ok": False, "available": False,
                    "reason": f"the analysis venv is missing at {ANALYSIS_PY}",
                    "readiness": {"ready": False, "state": "no-reading",
                                  "say": "The analysis sidecar is not installed.",
                                  "do": "See the entry's RUN.md — the venv is one command."}}
        argv = [str(ANALYSIS_PY), str(ANALYSIS / "run.py"), "watch",
                "--stream", str(STREAMS / device), "--seconds", str(seconds)]
        try:
            proc = subprocess.run(argv, capture_output=True, text=True, timeout=90,
                                  cwd=str(ANALYSIS))
        except subprocess.TimeoutExpired:
            return {"ok": False, "available": False,
                    "reason": "the reading took over 90 s — ask for a shorter --seconds",
                    "readiness": {"ready": False, "state": "no-reading",
                                  "say": "The reading timed out.", "do": "Try a shorter window."}}
        if proc.returncode != 0 or not proc.stdout.strip():
            # The LAST line of a traceback is the exception; the rest is this machine's paths.
            # Putting a whole traceback in an HTTP body is a path leak and unreadable besides.
            tail = (proc.stderr or "no output").strip().splitlines()
            return {"ok": False, "available": False,
                    "reason": (tail[-1] if tail else "no output")[:300],
                    "readiness": {"ready": False, "state": "no-reading",
                                  "say": "The reading failed.", "do": "Check the server log."}}
        try:
            return json.loads(proc.stdout)
        except json.JSONDecodeError as exc:
            return {"ok": False, "available": False, "reason": f"unreadable reading: {exc}"}


WATCH = WatchCache()


def _runbook_module():
    """`runbook.py` is stdlib on purpose, so this server imports it rather than shelling out.

    `watch.py` usually is not (it needs numpy and scipy), which is why the two halves of the claim page
    arrive by different routes. That is the seam, not an inconsistency: ticking a checkbox must not
    cost an interpreter start.
    """
    _analysis_on_path()
    from fieldlab import runbook
    return runbook


def _analysis_on_path() -> None:
    """Make the consumer's `fieldlab` package importable, once. Appended, so it can never shadow a
    module of this repo's (a consumer's own `bands.py` once could)."""
    if str(ANALYSIS) not in sys.path:
        sys.path.append(str(ANALYSIS))


class Handler(SimpleHTTPRequestHandler):
    server_version = "FieldLab/1"
    protocol_version = "HTTP/1.1"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(WEB), **kwargs)

    def log_message(self, fmt, *args):  # quieter
        if "/api/events" in str(args[0] if args else ""):
            return
        sys.stderr.write(f"{self.address_string()} - {fmt % args}\n")

    # -- routing helpers
    def _key(self) -> str:
        """The path with the gateway prefix removed, so routes work direct and proxied."""
        path = urlsplit(self.path).path
        for prefix in GATEWAY_PREFIXES:
            if path.startswith(prefix + "/") or path == prefix:
                path = path[len(prefix):] or "/"
        return path

    def _query(self) -> dict:
        return {k: v[-1] for k, v in parse_qs(urlsplit(self.path).query).items()}

    @staticmethod
    def _finite(value):
        """NaN and Infinity are not valid JSON and a browser rejects the whole document for one of
        them. Absence is the honest encoding of "not measured" — and this is the last line of
        defence, applied to every response rather than trusted to each producer."""
        if isinstance(value, float):
            return None if (value != value or value in (float("inf"), float("-inf"))) else value
        if isinstance(value, dict):
            return {k: Handler._finite(v) for k, v in value.items()}
        if isinstance(value, (list, tuple)):
            return [Handler._finite(v) for v in value]
        return value

    def _json(self, payload, status=200) -> None:
        body = json.dumps(self._finite(payload), allow_nan=False, default=str).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _error(self, status: int, message: str) -> None:
        self._json({"ok": False, "error": message}, status)

    def _body(self, limit: int = MAX_JSON_BYTES) -> bytes:
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0:
            return b""
        if length > limit:
            raise ValueError("body too large")
        return self.rfile.read(length)

    # -- static surface
    def end_headers(self):
        p = self._key()
        if p.startswith("/design/") or p.endswith((".css", ".js", ".html")) or p == "/":
            self.send_header("Cache-Control", "no-store")
        # CORS on READS ONLY. Other projects' pages run on their own ports, so a page on 8204
        # fetching the live stream from 8212 is cross-origin and blocked without this -- which is
        # the whole point of the tool being shared.
        #
        # Writes are closed to other origins by `do_POST`, not here: withholding allow-origin only
        # stops a page READING a response, and a cross-origin POST is still sent. Requiring a
        # JSON or chunk Content-Type forces a preflight, and OPTIONS never allows one.
        if self.command in ("GET", "HEAD", "OPTIONS"):
            self.send_header("Access-Control-Allow-Origin", "*")
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Methods", "GET, HEAD, OPTIONS")
        self.send_header("Content-Length", "0")
        self.end_headers()

    def translate_path(self, path):
        clean = path.split("?", 1)[0].split("#", 1)[0]
        # The consumer client is served from the TOOL root, not web/, so every project takes one
        # copy from here and they cannot drift -- the same arrangement `eeg-bridge` uses for
        # `eeg-client.js`. See INTEGRATION.md.
        if self._key() == "/fieldlab-client.js":
            return str(HERE / "fieldlab-client.js")
        for prefix in GATEWAY_PREFIXES + ("",):
            key = clean[len(prefix):] if prefix and clean.startswith(prefix) else clean
            if key in DESIGN_PUBLIC:
                return str(DESIGN_PUBLIC[key])
            if key.startswith("/design/fonts/"):
                name = key[len("/design/fonts/"):]
                if "/" not in name and ".." not in name and name.endswith(".woff2"):
                    f = (DESIGN / "fonts" / name).resolve()
                    if f.is_file() and f.parent == (DESIGN / "fonts").resolve():
                        return str(f)
        key = self._key() if clean == urlsplit(self.path).path else clean
        # The consuming entry's own claim page, mounted from outside this folder. Only the file
        # types a page is made of, no traversal, and no directory listing -- CLAIM_WEB sits inside
        # a study folder that also holds analysis code and cached data.
        if key == "/watch" or key.startswith("/watch/"):
            name = key[len("/watch"):].lstrip("/") or "index.html"
            if "/" not in name and ".." not in name and name.endswith((".html", ".css", ".js")):
                candidate = (CLAIM_WEB / name).resolve()
                if candidate.is_file() and candidate.parent == CLAIM_WEB.resolve():
                    return str(candidate)
            return "/dev/null/blocked"
        # The data folder and the server's own source are not on the URL surface.
        if "/streams/" in key or key.endswith("/streams") or key.endswith(".py") or "/analysis/" in key:
            return "/dev/null/blocked"
        if key == "/":
            key = "/index.html"
        # Everything else is a file inside web/. Resolving first is what stops `/../` reaching the
        # rest of the disk; the name checks above are case-sensitive and cannot do that alone.
        candidate = (WEB / key.lstrip("/")).resolve()
        if WEB.resolve() not in candidate.parents:
            return "/dev/null/blocked"
        return str(candidate)

    # -- verbs
    def do_GET(self):
        key = self._key()
        q = self._query()
        if key == "/watch":
            # Redirect to the trailing slash so the page's own relative paths resolve: `watch.js`
            # must become /watch/watch.js, and `../design/design.css` must become /design/...
            # Without this the page loads and every asset 404s, which looks like a broken server.
            self.send_response(301)
            self.send_header("Location", urlsplit(self.path).path + "/"
                             + (("?" + urlsplit(self.path).query) if urlsplit(self.path).query else ""))
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        if key == "/api/status":
            return self._json(STORE.status())
        if key == "/api/bands":
            return self._json({"source": str(BAND_REGISTRY_SWIFT.relative_to(HERE)), "bands": bands_from_swift()})
        if key == "/api/interference":
            phil = re.search(r'philosophy = "([^"]*)"', INTERFERENCE_SWIFT.read_text())
            return self._json({"source": str(INTERFERENCE_SWIFT.relative_to(HERE)),
                               "philosophy": phil.group(1) if phil else "",
                               "sources": interference_from_swift()})
        if key == "/api/streams":
            device = q.get("device", "")
            if not _valid_id(device):
                return self._error(400, "device")
            return self._json({"device": device, "streams": [STORE.stream_summary(device, s) for s in STORE.streams(device)]})
        if key == "/api/samples":
            device = q.get("device", "")
            if not _valid_id(device):
                return self._error(400, "device")
            try:
                now = time.time()
                t1 = float(q.get("to") or now)
                t0 = float(q.get("from") or (t1 - 60))
                step = max(1, int(q.get("step") or 1))
            except ValueError:
                return self._error(400, "from/to/step must be epoch seconds / int")
            if not (math.isfinite(t0) and math.isfinite(t1) and t0 <= t1):
                return self._error(400, "from/to must be finite, with from <= to")
            if t1 - t0 > 6 * 3600 and step < 10:
                return self._error(400, "a window over 6 h needs step >= 10 — ask for bins, not every sample")
            stream = q.get("stream")
            if stream and not _valid_id(stream):
                return self._error(400, "stream")
            return self._json(STORE.samples(device, t0, t1, step, stream))
        if key == "/api/findings":
            # Everything this entry has MEASURED, assembled offline by `run.py summary` from
            # cached artefacts. Served as a plain file because this server is stdlib-only and the
            # assembly needs numpy -- the same split as every other analysis route here.
            path = HERE / "data" / "findings.json"
            if not path.is_file():
                return self._json({
                    "available": False,
                    "reason": "data/findings.json has not been generated",
                    "how": "analysis/run.py summary"})
            try:
                return self._json(json.loads(path.read_text()))
            except Exception as exc:
                return self._error(500, f"findings.json unreadable: {exc}")
        if key == "/api/station":
            device = q.get("device", "")
            if not _valid_id(device):
                return self._error(400, "device")
            return self._json(LATEST_STATION.get(device) or {"device": device, "station": None})
        if key == "/api/register":
            device = q.get("device", "")
            if not _valid_id(device):
                return self._error(400, "device")
            _analysis_on_path()
            try:
                from fieldlab import autotests, register as reg
            except Exception as exc:  # noqa: BLE001 — the sidecar is an optional sibling
                return self._error(503, f"analysis sidecar unavailable: {exc}")
            data = reg.summary(STREAMS, device)
            for sig in data["signals"]:
                sig["outstanding"] = reg.outstanding(sig, list(autotests.MANUAL_TESTS))
            return self._json(data)
        if key == "/api/claim":
            # What the CONSUMING project adds to this generic viewer, declared by it rather than
            # decided here. The recorder draws what the phone recorded; a claim page draws what
            # somebody thinks it means, and those are different jobs that were sharing one
            # dashboard. A consumer with no claim.json gets `declared: false` and a clean device
            # viewer -- which is what the second consumer of this tool should see on day one.
            path = CLAIM_WEB / "claim.json"
            if not path.is_file():
                return self._json({"declared": False,
                                   "reason": "the consuming analysis ships no watch/claim.json",
                                   "analysis": ANALYSIS.name})
            try:
                data = json.loads(path.read_text())
            except ValueError as exc:
                return self._error(500, f"claim.json unreadable: {exc}")
            data["declared"] = True
            return self._json(data)
        if key == "/api/watch":
            device = q.get("device", "")
            if not _valid_id(device):
                return self._error(400, "device")
            try:
                seconds = int(float(q.get("seconds") or 300))
            except ValueError:
                return self._error(400, "seconds must be a number")
            seconds = max(30, min(seconds, 3600))
            return self._json(WATCH.get(device, seconds))
        if key == "/api/runbook":
            device = q.get("device", "")
            if not _valid_id(device):
                return self._error(400, "device")
            try:
                runbook = _runbook_module()
            except Exception as exc:  # noqa: BLE001 — the sidecar is an optional sibling
                return self._error(503, f"analysis sidecar unavailable: {exc}")
            # The readiness gate comes from the SAME cached reading the page is showing, so a step
            # can never be greyed out against a different window than the one on screen.
            try:
                seconds = max(30, min(int(float(q.get("seconds") or 300)), 3600))
            except ValueError:
                return self._error(400, "seconds must be a number")
            reading = WATCH.get(device, seconds)
            signal = None
            try:
                from fieldlab import register as reg
                claim_hz = reading.get("claim_hz")      # the study's watch reading names its line
                for sig in reg.summary(STREAMS, device).get("signals", []) if claim_hz is not None else []:
                    if abs(float(sig.get("frequency_hz", 0)) - float(claim_hz)) < 0.25:
                        signal = sig
                        break
            except Exception:  # noqa: BLE001 — a missing register means no recorded outcome yet
                signal = None
            which = q.get("which", "tests")
            if which not in ("tests", "acquisition"):
                return self._error(400, "which must be 'tests' or 'acquisition'")
            plan = runbook.plan(STREAMS, device, reading.get("readiness"), signal, which)
            plan["which"] = which
            plan["window"] = reading.get("window")
            plan["available"] = bool(reading.get("available"))
            plan["signal_id"] = (signal or {}).get("id")
            return self._json(plan)
        if key == "/api/alerts":
            device = q.get("device", "")
            if not _valid_id(device):
                return self._error(400, "device")
            return self._json(LATEST_ALERTS.get(device) or {"device": device, "alerts": None})
        if key == "/api/jobs":
            return self._json({"jobs": JOBS.list(), "commands": ANALYZE_COMMANDS, "venv": ANALYSIS_PY.exists()})
        if key == "/api/events":
            return self._events()
        if key.startswith("/api/"):
            return self._error(404, "no such route")
        # The gateway redirects bare /slug to /slug/; direct callers get the page either way.
        return super().do_GET()

    def do_POST(self):
        key = self._key()
        ctype = (self.headers.get("Content-Type") or "").split(";", 1)[0].strip().lower()
        if ctype not in POST_CONTENT_TYPES:
            return self._error(415, f"POST needs Content-Type {' or '.join(POST_CONTENT_TYPES)}")
        try:
            if key == "/api/stream/chunk":
                body = self._body(MAX_CHUNK_BYTES)
                if not body:
                    return self._error(400, "empty body")
                compression = self.headers.get("X-FieldLab-Compression", "deflate-raw")
                try:
                    return self._json(STORE.ingest(body, compression))
                except ChunkConflict as exc:
                    return self._error(409, str(exc))
                except ValueError as exc:
                    return self._error(422, str(exc))
            if key == "/api/stream/hello":
                try:
                    payload = json.loads(self._body() or b"{}")
                    return self._json(STORE.hello(payload))
                except (ValueError, json.JSONDecodeError) as exc:
                    return self._error(422, str(exc))
            if key == "/api/register/confirm":
                # A manual test only becomes a control once a person says they ran it. This is the
                # route that records that, and it appends rather than overwrites — a source that
                # vanished on Tuesday and not on Friday is the most interesting result there is.
                try:
                    payload = json.loads(self._body() or b"{}")
                    device = payload.get("device", "")
                    if not _valid_id(device):
                        return self._error(400, "device")
                    _analysis_on_path()
                    from fieldlab import register as reg
                    updated = reg.confirm_manual_test(
                        STREAMS, device, str(payload["signal"]), str(payload["test"]),
                        str(payload["outcome"]), str(payload.get("note", ""))[:500])
                    STORE.publish("register", {"device": device, "signal": updated["id"]})
                    return self._json({"ok": True, "signal": updated})
                except KeyError as exc:
                    return self._error(400, f"missing or unknown: {exc}")
                except (ValueError, json.JSONDecodeError) as exc:
                    return self._error(400, str(exc))
            if key in ("/api/runbook/step", "/api/runbook/reset"):
                try:
                    payload = json.loads(self._body() or b"{}")
                    device = payload.get("device", "")
                    if not _valid_id(device):
                        return self._error(400, "device")
                    runbook = _runbook_module()
                    if key.endswith("/reset"):
                        data = runbook.reset(STREAMS, device, str(payload["test"]),
                                             str(payload.get("why", ""))[:200])
                    else:
                        # The gate state is taken from the SERVER's cached reading, never from the
                        # browser. A page that has been open since this morning would otherwise
                        # stamp a step with a gate state from hours ago, and that stamp is the
                        # whole point of recording it.
                        state = (WATCH.get(device, 300).get("readiness") or {}).get("state")
                        data = runbook.check(STREAMS, device, str(payload["test"]),
                                             str(payload["step"]),
                                             bool(payload.get("done", True)),
                                             str(payload.get("note", ""))[:500], state)
                    STORE.publish("runbook", {"device": device, "test": payload.get("test")})
                    return self._json({"ok": True,
                                       "progress": runbook.progress(data, str(payload["test"]))})
                except KeyError as exc:
                    return self._error(400, f"missing or unknown: {exc}")
                except (ValueError, json.JSONDecodeError) as exc:
                    return self._error(400, str(exc))
                except Exception as exc:  # noqa: BLE001
                    return self._error(503, f"analysis sidecar unavailable: {exc}")
            if key == "/api/analyze":
                try:
                    payload = json.loads(self._body() or b"{}")
                    extra = [str(x) for x in payload.get("extra", [])][:8]
                    allowed = ("--radius", "--centre", "--events", "--shape-surrogates",
                               "--surrogates", "--alpha", "--against", "--archive",
                               "--station-month", "--member")
                    if any(x.startswith("-") and x not in allowed for x in extra):
                        return self._error(400, f"extra flags limited to {'/'.join(allowed)}")
                    return self._json(JOBS.start(payload.get("command", ""), payload.get("device", ""),
                                                 float(payload["from"]), float(payload["to"]), extra))
                except (KeyError, ValueError, json.JSONDecodeError, TypeError) as exc:
                    return self._error(400, str(exc))
            return self._error(404, "no such route")
        except ValueError as exc:
            return self._error(413, str(exc))

    def _events(self):
        q = STORE.subscribe()
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Connection", "keep-alive")
        self.send_header("X-Accel-Buffering", "no")
        self.end_headers()
        try:
            self.wfile.write(b"event: hello\ndata: " + json.dumps({"now": time.time()}).encode() + b"\n\n")
            self.wfile.flush()
            while True:
                try:
                    event, data = q.get(timeout=5.0)
                    self.wfile.write(f"event: {event}\ndata: {json.dumps(data)}\n\n".encode())
                except queue.Empty:
                    self.wfile.write(b"event: hb\ndata: " + json.dumps({"now": time.time()}).encode() + b"\n\n")
                self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError, OSError):
            pass
        finally:
            STORE.unsubscribe(q)


def main() -> None:
    port = int(sys.argv[1]) if len(sys.argv) > 1 else int(os.environ.get("PORT", DEFAULT_PORT))
    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    server.daemon_threads = True
    print(f"FieldLab stream server on http://127.0.0.1:{port}/  (store: {STREAMS})", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
